
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvxoldaymrvwayhwwyym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2eG9sZGF5bXJ2d2F5aHd3eXltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDg5NDIyMTcsImV4cCI6MjA2NDUxODIxN30.B-9Hi8CjSp91z0tnxJWk8aTqpunEYu1aYh6n8HYU0Lg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    autoRefreshToken: true,
    persistSession: true,
    detectSessionInUrl: true,
  },
});
